### ISSUE TITLE
New token format

### ISSUE THREAD

**Issue by matmsa27** [Ilhasoft/engine-whatsapp-demo#4]
Maybe we need to think of a new token format, a token more readable for example, it can be a project following a random string, just ideas.

**Comment by rasoro** [comment]
i think it could be like this <orgname-whatsapp-demo-shortid>.
eg: foo-whatsapp-demo-VVDvc6i99J

up to the shortid all characters should be lowercase and if the org name have two or more words it could be joined eg: Foo Bar -> foobar

**Comment by matmsa27** [comment]
Nice @rasoro , I totally agree with you, especially if all the characters will be in the lowercase, `foobar-whatsapp-demo-vvdvc6i99j`
